version: '{build}'
skip_tags: true
image:
- Visual Studio 2019
- Ubuntu
configuration: Release
test: off
#install:
#- ps: ./Setup.ps1
build_script:
- ps: ./Build.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
#  install:
#  - sh setup.sh
  build_script:
  - sh build.sh
artifacts:
- path: artifacts/Serilog.*.nupkg
- path: artifacts/Serilog.*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: pvGk80Hl+hnqiV0ucxBI2ZkYUlR6l7TrGZek37OCFh9Fro4BOhEBI2+UMkDwtgjt
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact:
    /Serilog.*\.nupkg/
    /Serilog.*\.snupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
